In [3]:
import numpy as np
filedata = np.genfromtxt('num.txt',delimiter=",")

**Loading Data from file**

In [6]:
filedata.astype('int32')

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90],
       [ 20,  40,  60,  80, 100, 120, 140, 160, 180]], dtype=int32)

**Boolean Masking**

In [4]:
filedata>50

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True,  True,  True,  True]])

In [5]:
filedata[filedata>40]

array([ 50.,  60.,  70.,  80.,  90.,  60.,  80., 100., 120., 140., 160.,
       180.])