In [2]:
import numpy as np

In [4]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.min(stats,axis=1)

array([1, 4])

In [9]:
np.sum(stats)

np.int64(21)

**Re-organizing Arrays**

In [6]:
before = np.array([[1,2,3,4],[5,6,7,8]])
after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

vstack stands for vertical stack.
It stacks arrays vertically, i.e., row-wise.

In [10]:
np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

hstack stands for horizontal stack.
It stacks arrays horizontally, i.e., column-wise.