**Mathematics**

In [2]:
import numpy as np

In [13]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

**Array addition**

In [16]:
a+5

array([ 6,  7,  8,  9, 10])

**Array Subtraction**

In [15]:
a-5

array([-4, -3, -2, -1,  0])

**Array Multiplication**

In [8]:
m = a*2
m

array([ 4,  8, 12, 16, 20])

**Array Division**

In [20]:
m/2

array([ 2.,  4.,  6.,  8., 10.])

**Finding sin cos and tan**

In [21]:
p = np.array([1,2,3])
p

array([1, 2, 3])

In [22]:
np.cos(p)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [23]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [24]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [12]:
b = np.array([[1,2],[3,4]])
print(b.shape)
c = np.array([[5,6],[7,8]])
print(c.shape)

(2, 2)
(2, 2)


**To this kind of multiplication both shape of 2d array should be same**

In [13]:
b*c

array([[ 5, 12],
       [21, 32]])

In [16]:
d = np.array([[4,5],[6,7],[8,9]])
e = np.array([[1,2,3],[4,5,6]])
np.matmul(d,e)

array([[24, 33, 42],
       [34, 47, 60],
       [44, 61, 78]])

In [17]:
v = np.identity(3)
v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.linalg.det(v)

np.float64(1.0)