In [7]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[2.0,3.0,4.0],[7.0,8.0,9.0]])
print(b)

[[2. 3. 4.]
 [7. 8. 9.]]


In [5]:
c = np.array([[1,2,3],[4,5,6,],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#knowing shape of matrix
c.shape

(3, 3)

In [9]:
#knowing data type
a.dtype

dtype('int64')

In [10]:
d = np.array([[1.2,1.3,1.4],[1.5,1.6,1.7]])
print(d)


[[1.2 1.3 1.4]
 [1.5 1.6 1.7]]


In [11]:
d.dtype

dtype('float64')

In [26]:
 #accsessing,changing elements
e = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [20]:
e[3,0,1]

IndexError: index 3 is out of bounds for axis 0 with size 1

In [28]:
#Get a specific column
e[:,2]

array([ 3,  8, 13])

In [27]:
#Get a specific row

array([ 3,  8, 13])

In [3]:
f = np.array([[1,2,3],[4,5,6]])
print(f)

[[1 2 3]
 [4 5 6]]


In [ ]:
f[2,2]=[7]
print(f)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [10]:
m = np.array([
    [[1,2],[3,4]],[[5,6],[7,8]
]])
print(m)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
#Get specific element 
m[:,1,1]

array([4, 8])

In [13]:
m[:,1]

array([[3, 4],
       [7, 8]])