In [2]:
import numpy as np

#all zeros matrix array
z = np.zeros([2,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#aLl ones array
o = np.ones([2,2])
o

array([[99, 99],
       [99, 99]])

In [12]:
j = np.full([3,3],24)
j

array([[24, 24, 24],
       [24, 24, 24],
       [24, 24, 24]])

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a
# np.full_like(a,4)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [3]:

k = np.random.rand(2,3)
k

array([[0.01363955, 0.27136374, 0.8556789 ],
       [0.13481443, 0.51781556, 0.73786377]])