**Array Operations**

In [2]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

**Addition**

In [2]:
add = a+b
add

array([ 6,  8, 10, 12])

In [3]:
mul = a*b
mul

array([ 5, 12, 21, 32])

**Finding Exponential**

In [5]:
exp_a = np.exp(a)
exp_a

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [6]:
log_a = np.log(a)
log_a

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [3]:
a*b

array([ 5, 12, 21, 32])