**All zeros matrix array**

In [1]:
import numpy as np
z = np.zeros([2,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#aLl ones array
o = np.ones([2,2])
o

array([[99, 99],
       [99, 99]])

In [12]:
j = np.full([3,3],24)
j

array([[24, 24, 24],
       [24, 24, 24],
       [24, 24, 24]])

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a
# np.full_like(a,4)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

**Generating Decimal 2D Array**

In [3]:
k = np.random.rand(2,3)
k

array([[0.01363955, 0.27136374, 0.8556789 ],
       [0.13481443, 0.51781556, 0.73786377]])

In [4]:
#Random Integer Matrix
np.random.randint(7,size=(2,2))
#generate random integers from 0 (inclusive) to 7 (exclusive) — so values will be in the range

array([[5, 4],
       [2, 2]])

In [5]:
#Random integer matrix
np.random.randint(1,10,size=(3,3))

array([[5, 2, 2],
       [4, 8, 6],
       [2, 9, 7]])

In [6]:
#NEgative numbers in 2d array
np.random.randint(-9,0,size=(3,3))

array([[-4, -7, -2],
       [-1, -5, -8],
       [-8, -4, -2]])

**Repeating 2D Array elements**

In [8]:
#Repeating elements
ap = np.array([1,2,3])
r1 = np.repeat(ap,3,axis=0)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [11]:
ra = np.array([[1,2,3,4],[5,6,7,8]])
r2 = np.repeat(ra,2,axis=0)
r2
#axis = 0 (row)
#axis = 1 (column)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

**Printing Particular Pattern**

In [4]:
output = np.ones((5,5))
output[1:4,1:4] = 0
output[2,2] =9
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
pattern = np.ones((5,5))
zero = np.zeros((3,3))
zero
pattern[1:4,1:4] = zero
pattern

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**Copying Arrays**

In [ ]:

a = np.array([1,2,3,4,5])
b = a.copy()
b[0]=0
b